### ISSUE TITLE
keyszer cause the one key is keeping pressed not up.(e.g. or Ctrl or Alt or Any ascii)

### ISSUE THREAD

**Issue by zw963** [joshgoebel/keyszer#81] opened 2022-08-21 09:53 UTC
**Describe the bug or unexpected behavior**

It hard for me to find out why this issue happen.

But, when i start/top my keyszer service manually on command line, this issue happen frequently.

when this issue happen, I can not input some char, e.g. `s`, because pressing always result in `Ctrl+s`,
which cause my terminal stop.

I have to reboot my laptop too make keyszer continue works.

I remember this issue happen on xkeysnail too, (don't sure anyway)

**Sample Config or Instructions to Reproduce**

**Your setup**

- Python version: 3.10.6
- Keyszer version: 0.6.0
- Kinto version (if applicable): no
- Devices `(+K)` we're handling input from:

**Additional context**
I use on the latest GNOME + wayland in arch linux.

**Comment by joshgoebel** [comment] 2022-08-21 11:25
Please use the latest version from git.  For issues like this you really need to find the pattern. I can't do much unless you can tell me exactly how to reproduce. 

You may want to learn about and use the emergency eject and debugging keys though.

**Comment by zw963** [comment] 2022-08-21 18:26
> Please use the latest version from git.

Yes, i used latest.

I will try get more info when it happen next time, but, because some key not work when this happen,
i even can't kill my keyszer use `pkill keyszer`,  how can i exit this?

**Comment by joshgoebel** [comment] 2022-08-21 19:05
Configure the emergency eject key. Adios be in range or see config_api.

**Comment by zw963** [comment] 2022-08-22 05:36
Before i could not find the eject key out, same issue happen again, but this time is `Alt`, all i done is just change some config, and `systemctl --user restart keyszer`, some of my jobs is missing because i have to reboot my laptop.

Following is my service file:

```
[Unit]
Description=keyszer

[Service]
ExecStart=/home/zw963/utils/keyszer/bin/keyszer -c /home/zw963/utils/keyszer/config_new.py
Type=simple
Restart=always
RestartSec=2

[Install]
WantedBy=graphical.target
```

Any idea on a more robust service file? And could you please point out how to use emergency_eject_key ? i don't know what is the Key.F16? How can i specify use `Ctrl+Alt+q` ?

Thank you.

**Comment by RedBearAK** [comment] 2022-08-22 12:10
@zw963 

You can pick any key on your keyboard for the debug key, but it has to be a single key. not a combo. 

Place something like this in your config file, near the top. 

```python
# Keyszer-specific config settings
dump_diagnostics_key(Key.F7)
emergency_eject_key(Key.F8)
```

In this example I'm using the F7 key for diagnostics, and F8 for the emergency eject/debug key. Just pick a key on your keyboard that you never use for any other purpose.

**Comment by joshgoebel** [comment] 2022-08-22 14:11
@zw963 Often you can unstick a key by hitting it again (or it's remapped version)... For example if Ctrl is remapped to Alt and it gets "stuck" try hitting:

- ctrl 
- alt

Just pressing them all by themselves... often this will unstick the key.  What does your full config look like again?

**Comment by zw963** [comment] 2022-08-23 02:46
> Just pressing them all by themselves... often this will unstick the key. What does your full config look like again?

```python
from evdev import ecodes
from keyszer import output
from evdev.uinput import UInput

output._uinput.close()
_keyboard_codes = ecodes.keys.keys() - ecodes.BTN
# create a new device with the exact options you want to mimic
output._uinput =  UInput(events={ecodes.EV_KEY: _keyboard_codes,
                                 ecodes.EV_REL: set([0,1,6,8,9]),
                                 },
                         name="Keyszer VIRTUAL mykeyboarddevice",
                         phys="isa0060/serio0/input0",
                         vendor=1,
                         product=1,
                         version=43841,
                         bustype=17,
                         input_props=[])

modmap("caps as control", {
    Key.CAPSLOCK: Key.LEFT_CTRL,
    Key.RIGHT_ALT: Key.CAPSLOCK
})

emergency_eject_key("C-Alt-q")

keymap("Emacs-like keys", {
    C("C-b"): with_mark(C("left")),
    C("C-f"): with_mark(C("right")),
    C("C-p"): with_mark(C("up")),
    C("C-n"): with_mark(C("down")),
    C("Alt-b"): with_mark(C("C-left")),
    C("Alt-f"): with_mark(C("C-right")),

    C("C-a"): with_mark(C("home")),
    C("C-e"): with_mark(C("end")),

    C("Alt-v"): with_mark(C("page_up")),
    C("C-v"): with_mark(C("page_down")),

    C("Alt-Shift-comma"): with_mark(C("C-home")),
    C("Alt-Shift-dot"): with_mark(C("C-end")),

    C("C-d"): [C("delete"), set_mark(False)],
    C("Alt-d"): [C("C-delete"), set_mark(False)],
    C("Alt-Backspace"): [C("C-Backspace"), set_mark(False)],
    C("C-k"): [C("Shift-end"), C("C-x"), set_mark(False)],

    C("C-g"): [C("esc"), set_mark(False)],
    # C("C-q"): escape_next_key,

    C("C-slash"): [C("C-z"), set_mark(False)],

    # C("C-w"): [C("C-x"), set_mark(False)],
    C("Alt-w"): [C("C-c"), set_mark(False)],
    C("C-y"): [C("C-v"), set_mark(False)],

    C("C-KEY_2"): set_mark(True),
    C("C-Alt-space"): with_or_set_mark(C("C-right")),

    # 这个用 F3 不合适，因为在 Firefox 下面，如果上次已经搜索过，
    # 再次按下 F3, 则会使用上次的关键字继续搜索。
    # 这样没有机会更改关键字。
    C("C-s"): C("C-f"),

    C("C-x"): {
        C("h"): [C("C-home"), C("C-a"), set_mark(True)],
        C("C-f"): C("C-o"),
        C("C-s"): C("C-s"),
        C("C-c"): C("C-q"),
        C("C-g"): ignore_key,
    }
}, when = lambda ctx: ctx.wm_class not in ("Emacs", "konsole", "Bcompare4"))

```

**Comment by joshgoebel** [comment] 2022-08-23 12:16
>    Key.RIGHT_ALT: Key.CAPSLOCK

Caps Lock is NOT a modifier, so this could cause all sorts of problems.  It may work better if you turned it into a modifier:

```py
Modifier("CAPS", aliases = ["LCaps"], key = Key.CAPSLOCK)
```

> emergency_eject_key("C-Alt-q")

As already mentioned this may only be a single key:

`emergency_eject_key(Key.F9)`

**Comment by zw963** [comment] 2022-08-23 12:45
> > Key.RIGHT_ALT: Key.CAPSLOCK
> 
> Caps Lock is NOT a modifier. Mapping modifiers to non modifiers can cause roblems. It may work better if you turned it into a modifier:
> 
> ```python
> Modifier("CAPS", aliases = ["LCaps"], key = Key.CAPSLOCK)
> ```
> 
> > emergency_eject_key("C-Alt-q")
> 
> As already mentioned this may only be a single key:
> 
> ```python
> emergency_eject_key(Key.F9)
> ```

Okay, i change to this.

```
Modifier("CAPS", aliases = ["LCaps"], key = Key.CAPSLOCK)
modmap("caps as control", {
    Key.CAPSLOCK: Key.LEFT_CTRL,
    Key.RIGHT_ALT: Key.CAPSLOCK
})
emergency_eject_key(Key.F9)
```

It seem like good when i run `keyszer --check`.

BTW: why following config raise error when i do check ?

```
from evdev import ecodes
from keyszer import output
from evdev.uinput import UInput

output._uinput.close()
_keyboard_codes = ecodes.keys.keys() - ecodes.BTN
# create a new device with the exact options you want to mimic
output._uinput =  UInput(events={ecodes.EV_KEY: _keyboard_codes,
                                 ecodes.EV_REL: set([0,1,6,8,9]),
                                 },
                         name="Keyszer VIRTUAL mykeyboarddevice",
                         phys="isa0060/serio0/input0",
                         vendor=1,
                         product=1,
                         version=43841,
                         bustype=17,
                         input_props=[])
```

```
keyszer v0.6.0
(EE) CONFIG: No bueno, we have a problem...

Traceback (while executing your config):
  File "/home/zw963/utils/keyszer/config_new.py", line 5, in <module>
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by zw963** [comment] 2022-08-23 16:39
It seem like `emergency_eject_key(Key.F9)` not work, even, when i pressing this key unexpectedly, my Ctrl issue is happen again.(but, before pressing F9, it not happen)

>  Often you can unstick a key by hitting it again (or it's remapped version)... For example if Ctrl is remapped to Alt and it gets "stuck" try hitting:

It seem like this hack works sometimes, e.g. when Ctrl is keeping missing, i can input the `s` and `p` in my terminal.
I keep pressing `Ctrl` + `Alt`, and then `Ctrl + c`, several times, it probably get released, i try this several times.

**Comment by zw963** [comment] 2022-08-23 16:43
Hi, this issue happen very frequently in my GNOME + Wayland, so, we have to find a way to debug this, i don't know why it happen, but when this happen, if my another second keyboard can work, how to debug this issue?

**Comment by joshgoebel** [comment] 2022-08-24 01:41
Hook up the emergency diagnostic key and get some diag output the next time it glitches.

**Comment by joshgoebel** [comment] 2022-08-24 12:37
> output._uinput.close()  

Uinput isn't assigned yet.. hence the error that you're trying to call a method on `None`... you'd need to update your config to test first if uinput is set.

```py
if output._uinput:
  output._uinput.close()  
```

**Comment by joshgoebel** [comment] 2022-08-24 12:39
> It seem like emergency_eject_key(Key.F9) not work

You'll have to be more specific... hitting this key causes Keyzer to immediately exit... I've never seen it not work.  Of course if you're using it from a service or something it may be immediately restarted - but you'd see what happened in the log.

**Comment by joshgoebel** [comment] 2022-08-24 12:40
> GNOME + Wayland, 

Of course that's not really a supported config (yet) and none of the enhanced features we support will work.  But basic keymapping should still work.

**Comment by zw963** [comment] 2022-08-24 13:29
> > output._uinput.close()
> 
> Uinput isn't assigned yet.. (for --check) hence the error that you're trying to call a method on `None`... you'd need to update your config to test first if uinput is set.
> 
> ```python
> if output._uinput:
>   output._uinput.close()  
> ```

  do `output._uinput.close()` is still necessary?

i remember all done is for we want support Wayland's feature, disable touchpod when typing.

If it not necessory(uinput is not assigned yet, right?), i guess i can remove it.

**Comment by zw963** [comment] 2022-08-24 13:57
BTW: this issue is really annoied.

i guess i have to give up to try this, because this make my laptop almost not work.

```
Hook up the emergency diagnostic key and get some diag output the next time it glitches.
```

This never work up for me, because i can do nothing when this issue happen, maybe you can try on GNOME + Wayland to reproduce this?

**Comment by joshgoebel** [comment] 2022-08-24 16:07
> because i can do nothing when this issue happen

_All you have to do is hit the diagnostic key AND then the emergency eject._   This is why they aren't combos... they happen at the lowest input level so they work even if all other input is "wonky"...

I have never seen these keys not work.  If you have a laptop where the F keys are hidden behind `Fn` you may need to use that to press them... You can test this with `evtest` on the console...

If you're truly running into a case where the emergency keys don't work at all you'd need to troubleshoot it more and give me something to look into.

> maybe you can try on GNOME + Wayland to reproduce this?

I'm pretty sure it's something about setup or config, not your environment.  I'd suggest:

- go back to running keyzer in a console
- remove your whole config
- get emergency keys (both of them) working
- add back config little at a time

Now you should be able to get diagnostics AND eject... and that should help tracking down further issues.

**Comment by zw963** [comment] 2022-08-25 04:00
Okay, thanks for help, i have to start keyszer manually from my terminal instead user systemd, following is my full config:

```python
Modifier("CAPS", aliases = ["LCaps"], key = Key.CAPSLOCK)
modmap("caps as control", {
    Key.CAPSLOCK: Key.LEFT_CTRL,
    Key.RIGHT_ALT: Key.CAPSLOCK
})

dump_diagnostics_key(Key.F11)
emergency_eject_key(Key.F12)

keymap("Emacs-like keys", {
    C("C-b"): with_mark(C("left")),
    C("C-f"): with_mark(C("right")),
    C("C-p"): with_mark(C("up")),
    C("C-n"): with_mark(C("down")),
    C("Alt-b"): with_mark(C("C-left")),
    C("Alt-f"): with_mark(C("C-right")),

    C("C-a"): with_mark(C("home")),
    C("C-e"): with_mark(C("end")),

    C("Alt-Shift-comma"): with_mark(C("C-home")),
    C("Alt-Shift-dot"): with_mark(C("C-end")),

    C("C-d"): [C("delete"), set_mark(False)],
    C("Alt-d"): [C("C-delete"), set_mark(False)],
    C("Alt-Backspace"): [C("C-Backspace"), set_mark(False)],
    C("C-k"): [C("Shift-end"), C("C-x"), set_mark(False)],

    C("C-g"): [C("esc"), set_mark(False)],

    C("C-slash"): [C("C-z"), set_mark(False)],

    # C("C-w"): [C("C-x"), set_mark(False)],
    C("Alt-w"): [C("C-c"), set_mark(False)],
    C("C-y"): [C("C-v"), set_mark(False)],

    C("C-KEY_2"): set_mark(True),
    C("C-Alt-space"): with_or_set_mark(C("C-right")),

    C("C-s"): C("C-f"),
}, when = lambda ctx: ctx.wm_class not in ("Emacs", "konsole", "Bcompare4"))
```

**Comment by zw963** [comment] 2022-08-25 04:11
BTW, i guess there exists another bug, right? i describe it here, if is true, i will create a new issue.

```sh
 ╰─ $ keyszer --list-devices
keyszer v0.6.0
-----------------------------------------------------------------------------------
Device               Name                                Phys
-----------------------------------------------------------------------------------
/dev/input/event0    Lid Switch                          PNP0C0D/button/input0
/dev/input/event1    Power Button                        PNP0C0C/button/input0
/dev/input/event2    Sleep Button                        PNP0C0E/button/input0
/dev/input/event3    Power Button                        LNXPWRBN/button/input0
/dev/input/event4    AT Translated Set 2 keyboard        isa0060/serio0/input0
/dev/input/event5    MOSART Semi. wireless dongle        usb-0000:00:14.0-4/input0
/dev/input/event6    MOSART Semi. wireless dongle Mouse  usb-0000:00:14.0-4/input1
/dev/input/event7    MOSART Semi. wireless dongle Consumer Control
                                                         usb-0000:00:14.0-4/input1
/dev/input/event8    MOSART Semi. wireless dongle System Control
                                                         usb-0000:00:14.0-4/input1
/dev/input/event9    MOSART Semi. wireless dongle        usb-0000:00:14.0-4/input1
/dev/input/event10   MOSART Semi. wireless dongle        usb-0000:00:14.0-4/input1
/dev/input/event11   LG WMI hotkeys                      wmi/input0
/dev/input/event12   PC Speaker                          isa0061/input0
/dev/input/event13   LG Camera: LG Camera                usb-0000:00:14.0-6/button
/dev/input/event14   04CA00B1:00 04CA:00B1 Touchpad      i2c-04CA00B1:00
/dev/input/event15   04CA00B1:00 04CA:00B1 Mouse         i2c-04CA00B1:00
/dev/input/event16   Video Bus                           LNXVIDEO/video/input0
/dev/input/event17   HDA Intel PCH Mic                   ALSA
/dev/input/event18   HDA Intel PCH Headphone             ALSA
/dev/input/event19   HDA Intel PCH HDMI/DP,pcm=3         ALSA
/dev/input/event20   HDA Intel PCH HDMI/DP,pcm=7         ALSA
/dev/input/event21   HDA Intel PCH HDMI/DP,pcm=8         ALSA
/dev/input/event22   HDA Intel PCH HDMI/DP,pcm=9         ALSA
/dev/input/event23   HDA Intel PCH HDMI/DP,pcm=10        ALSA
/dev/input/event24   Keyszer (virtual) Keyboard          py-evdev-uinput

 ╰─ $ command ls -t /dev/input/by-path/*-kbd
/dev/input/by-path/pci-0000:00:14.0-usb-0:4:1.0-event-kbd  
/dev/input/by-path/platform-i8042-serio-0-event-kbd

 ╰─ $ readlink -e /dev/input/by-path/pci-0000:00:14.0-usb-0:4:1.0-event-kbd
/dev/input/event5

 ╰─ $ readlink -e /dev/input/by-path/platform-i8042-serio-0-event-kbd
/dev/input/event4

```

As you can see, i use two keyboard.

When i run keyszer, i use command like this:

```
keyszer -d /dev/input/event5 -c /home/zw963/utils/keyszer/bin/..//config_new.py

```

So, it should only map on /dev/input/event5, right?

But, the fact is, when the pressing issue happen, both of my keyboard all get stuck.

Following is output log when run from terminal

```sh
keyszer v0.6.0
(DD) CONFIG: /home/zw963/utils/keyszer/bin/..//config_new.py

(II) in LEFT_SHIFT (press)
(DD) on_key LEFT_SHIFT press
(DD) suspending keys [LShift<Key.LEFT_SHIFT>]

(II) in LEFT_SHIFT (release)
(DD) on_key LEFT_SHIFT release
(DD) resume because of mod release
(DD) resuming keys: [<Key.LEFT_SHIFT: 42>]
(OO) press LEFT_SHIFT
(OO) release LEFT_SHIFT
(+K) Grabbing MOSART Semi. wireless dongle (/dev/input/event5)
(--) Ready to process input.
```

**Comment by joshgoebel** [comment] 2022-08-25 05:07
Now test both the emergency keys and make sure they are working.

**Comment by zw963** [comment] 2022-08-25 08:13
Okay, this issue happen again, following is log then i pressing dump and emergency keys:

```
keyszer v0.6.90
(+K) Grabbing MOSART Semi. wireless dongle (/dev/input/event5)
(--) Ready to process input.
*** TRANSFORM  ***
are we suspended: False
_suspend_timer:
None
_last_key:
BACKSPACE
_key_states:
{}
_sticky:
{}
*** OUTPUT ***
_pressed_modifier_keys:
set()
_pressed_keys
set()
_suspended_mod_keys
[]
_suspend_depth 0

^[[23;3~(EE) BAIL OUT: Emergency eject - shutting down.

```

**Comment by joshgoebel** [comment] 2022-08-25 12:10
>  this issue happen again, 

Your going to have to find the pattern and steps to reproduce.

>  following is log

This is nothing "stuck" in that diag... it looks perfectly fine... if a key was stuck it would appear in the diagnostic output even if that key had been lifted.

**Comment by joshgoebel** [comment] 2022-08-27 15:39
@RedBearAK Do you still run into any/many stuck key issues these days?  I wonder if perhaps a 3rd emergency key to reset the internal state might be useful?

**Comment by RedBearAK** [comment] 2022-08-27 21:59
> @RedBearAK Do you still run into any/many stuck key issues these days? I wonder if perhaps a 3rd emergency key to reset the internal state might be useful?

@joshgoebel 

I am fairly certain that I do on occasion, but ever since I started setting the menu bar to "hidden" in VSCodes and disabling the Alt key for the menu in Firefox settings, I'm having a hard time recalling when it was a real issue. 

The main symptoms before were in VSCode, where I would Cmd+Tab (Alt+Tab) from somewhere else and find that clicks or arrow keys would act like I was holding down the Alt key. My suspend timer is still just 0.1s due to the touchpad click issue, but the stuck modifiers doesn't seem to be much of a problem lately. 

One problem with setting up yet another emergency key is that laptops don't tend to have much available that doesn't have some other function. So besides the Escape key, what could laptop users really pick for that? In which case why not just generally task the Escape key with sending release events? (But they changed the title here to say "Ctrl or Alt or Any ascii, so you'd have to send release events for the entire keyboard.)

Doesn't evdev see three possible key states, press, repeat and release? I feel like a timer that makes sure there are "repeat" events happening constantly for a key that's "down" and sends a "release" if no "repeat" events are seen within a reasonable time frame would go a long way to resolving stuck keys. 

But I also wonder in this case if the issue this user was having with "slow" keys, which actually appeared to be rapidly repeating keys with the repeat delay set to 0ms, was ever resolved. Surely that could have something to do with this issue of various keys appearing to be "stuck". Seems this issue for them is not just about a modifier key getting stuck sometimes. 

That thing with VSCode always seemed to happen right after Alt+Tabbing in from another application, as if the "bind" didn't quite make it through the changing of the keymap from one app to another. Or, the "bind" did work, somehow making VSCode believe that I had pressed Alt and not released it. But I have no further insight into the matter.

**Comment by joshgoebel** [comment] 2022-08-29 11:17
> Any ascii

This is definitely not a keyzser issue (Afaik) since we don't "hold down" non-modifiers... I've never seen any issues with regular keys, period - the entire time I've been developing on this.

**Comment by joshgoebel** [comment] 2022-08-29 11:45
@zw963 I'll leave this open a while (for others to find it and contribute) but eventually if that doesn't happen and you can't provide instructions to reproduce we may have to close this as a problem unique to your exact hardware/setup, not the software in general.

Most issues so far have been *very* reproducible - ie, non-random.... so if one pays attention carefully you can find the pattern... and then write down a sequence of 3-4 steps to "make it break"... at that point it's usually pretty easy to track down the bug and fix it... 

I'm also be open to suggestions to improve logging to make these things easier for users to track down... perhaps we always keep the past 2 minutes of logs and when something bad happens one can "dump" them with a keystroke? @RedBearAK Any ideas here?

**Comment by joshgoebel** [comment] 2022-08-29 12:03
> One problem with setting up yet another emergency key is that laptops don't tend to have much available that doesn't have some other function. 

These keys are for users helping to develop/debug the app... they don't have to set ALL the emergency keys at once - they can set only the useful ones.  They may need to get an external keyboard if they truly have NO keys they can "give up" in the short-term.

It's not expected that most regular users of the app would ever use (or configure) these keys... esp once we hit 1.0.

**Comment by RedBearAK** [comment] 2022-08-29 12:03
@joshgoebel 

> perhaps we always keep the past 2 minutes of logs and when something bad happens one can "dump" them with a keystroke?

That's not a bad idea, although when weird things are happening that could include quite a lot of events. Might make more sense to buffer the most recent NNN number of lines of log output or something like that. 

I really think this user's issue has something to do with the repeating key problem they were having originally. Or as they described it, xkeysnail/keyszer being "too slow" on their relatively high-end PC, which is of course patently ridiculous, since these apps work perfectly on a 2GB Raspberry Pi. It seemed much more like they had keys repeating because something was happening much too fast, like the keyboard delay somehow being set to 0ms. 

This user has also mentioned Wayland, and Wayland still has all sorts of weird bugs. I have to wonder if that has something to do with what they keep experiencing. 

I can still trigger a terminal repeating loop myself with Ctrl+C that forces me to close the terminal tab, so it's not like it's impossible for something to be getting stuck. But I don't have a good technique for troubleshooting it at the moment.

**Comment by joshgoebel** [comment] 2022-08-29 12:06
>  if no "repeat" events are seen within a reasonable time frame would go a long way to resolving stuck keys.

This is not reliable... key repeat only works if NO other keys are pressed... as soon as you press a key "inbetween" you shut off the previous key-repeat....

- Ctrl hold (which sends repeats)
- press "B" and release
- Ctrl is still held, but no more repeats

**Comment by RedBearAK** [comment] 2022-08-29 12:08
> > if no "repeat" events are seen within a reasonable time frame would go a long way to resolving stuck keys.
> 
> This is not reliable... key repeat only works if NO other keys are pressed... as soon as you press a key "inbetween" you shut off the previous key-repeat....
> 
>     * Ctrl hold (which sends repeats)
> 
>     * press "B" and release
> 
>     * Ctrl is still held, but no more repeats

Oh, I see. Odd. If the repeats just stop, that's not very useful.

**Comment by joshgoebel** [comment] 2022-09-03 22:28
@zw963 Have you found any additional information or steps to reproduce this yet?  You also never confirmed if you'd upgraded to 0.6.91....

**Comment by zw963** [comment] 2022-09-04 03:40
> You also never confirmed if you'd upgraded to 0.6.91....

I use git repo directly as binary, so, most of time, always newest version.

Because systemd always restart, i disable it, i will start it again on system boot, i will give some feedback soon.

Thank you.

**Comment by joshgoebel** [comment] 2022-09-06 18:58
Can be reopened if later if additional information to reproduce is provided or it seems like others are having the same issue.

**Closed by joshgoebel** 2022-09-06 18:58 UTC
Labels: bug, help welcome, autoclose

**Comment by zw963** [comment] 2022-09-15 09:44
This issue seem like not happen any more since f5c5f67.

i need more time to ensure not fix by others reason.

**Comment by zw963** [comment] 2022-09-15 10:25
Sad, i happen again,  probably because I haven't tested it much recently, so it looks good.
