### ISSUE TITLE
Task switcher getting stuck open or failing to appear

### ISSUE THREAD

**Issue by RedBearAK** [joshgoebel/keyszer#18] opened 2022-06-09 01:10 UTC
@joshgoebel 

Just loaded up the latest `keyszer` and I'm seeing something I haven't really seen before. If I do Cmd+Shift+Tab, the task switcher won't even show up. And the switch is immediate. 

If I start with Cmd+Tab and then do Cmd+Shift+Tab, the task switcher gets stuck open on screen until I hit Enter or tap the "Option" (Super/Win remapped to Alt on PC) key. Tapping the other modifiers doesn't do anything. 

Don't recall seeing either of these behaviors on previous iterations of `keyszer`. 

(Looks like you're not getting automatically added to new issues in this repo? Says "No one assigned" in the sidebar.)

**Comment by RedBearAK** [comment] 2022-06-09 01:50
@joshgoebel 

Also, if I try to hit Escape, it acts like I'm hitting Alt+Esc. I'm not exactly sure what it's doing, there's a purple outline around the window and it seems to switch to a different window kind of like Alt+Tab. 

So it really seems like it's not sending a release for "Alt" for some reason.

**Comment by joshgoebel** [comment] 2022-06-09 05:31
I'd probably go back to the last revision that you had working for now (if you want)... I'm pretty much rewriting a lot of things now to fix multi modmaps and build them on the same asyncio foundation of suspend/resume.  I can ping ya in a few days when I have something more stable.  Not sure why things broke for you though - I didn't test much after the rename.

**Comment by joshgoebel** [comment] 2022-06-09 19:38
I plan to publish 0.5 in a few days with an official changelog and all that jazz.  I need to write a few more tests first then kill my running copy and upgrade myself.

**Comment by joshgoebel** [comment] 2022-06-10 00:51
I just killed my old copy and fired up the new one with all the changes and seems pretty smooth for me so far.

**Comment by joshgoebel** [comment] 2022-06-11 22:25
Any update, did you every get 0.5.0 up and running?

**Comment by RedBearAK** [comment] 2022-06-12 00:46
>Any update, did you every get 0.5.0 up and running?

Just tried the latest pull, after swapping out all the `M` references in my config file. It ran after that, but I wound up with no output or exceptions from any keyboard event, and no action from any keyboard event. Yes, I keep forgetting to edit the input and set up a debug key that might be available on my keyboard. Have to remember to add that to my startup script. Anyway, there were no error messages being displayed so the fact that I had to close the terminal tab again to get keyboard control back is irrelevant.

**Comment by joshgoebel** [comment] 2022-06-12 00:49
So weird... I assume you tried a fresh install?  Are you running in `--verbose` mode?

**Comment by RedBearAK** [comment] 2022-06-12 00:56
I just re-enabled the lines that remove the directory and do the whole clone and everything again, to see if that makes a difference. 

```
keyszer: error: unrecognized arguments: --verbose
```

Confused, as usual.

**Comment by joshgoebel** [comment] 2022-06-12 00:58
Ha I think I simplified... `-h` as always... `-v`... there is no long form.

**Comment by RedBearAK** [comment] 2022-06-12 00:59
I was about to try that, actually, thinking maybe you misremembered putting the long one in.

**Comment by RedBearAK** [comment] 2022-06-12 01:09
Ok, with the `-v` in there, I see the output going completely **_bonkers_** as soon as I try a "combo" like Cmd+Space (logical Alt+F1, physical Alt+Space). Looks like a loop of press/release events of the same keys scrolling by quite rapidly. Other shortcuts will show different things briefly but the stream continues with the original shortcut events so anything else disappears in a flash. A photo would not do it justice. I'd need to activate the debug key to get it to stop and preserve the output. 

Still with the "no keyboard" effect while this is happening. It doesn't even successfully bring up the app launcher tied to that shortcut, or maybe it's activating and deactivating the shortcut so rapidly that nothing appears to be happening, and nothing else can happen either. 

Debugging. It's Always an Adventure™.

**Comment by joshgoebel** [comment] 2022-06-12 01:12
Don't start with combos, start with something simpler like a b c... easy things... as always getting me some logging would be great.

**Comment by joshgoebel** [comment] 2022-06-12 01:14
```
(II) in A (press)
(DD) on_key A press
(OO) press A
a(II) in A (release)
(DD) on_key A release
(OO) release A
(II) in B (press)
(DD) on_key B press
(OO) press B
b(II) in B (release)
(DD) on_key B release
(OO) release B
(II) in C (press)
(DD) on_key C press
(OO) press C
c(II) in C (release)
(DD) on_key C release
(OO) release C
```

**Comment by joshgoebel** [comment] 2022-06-12 01:15
What version of python?

**Comment by joshgoebel** [comment] 2022-06-12 01:23
I'm running the same software straight for days (with periodic restarts as I add new features and close out issues)... so it's proving 100% rock solid on my end.  Very curious to finally find out what issue you're running into.

**Comment by RedBearAK** [comment] 2022-06-12 02:09
I might have something missing from my path because I can't just run "pytest", even though all of that is installed. I tried with `python3 -m pytest` and the results did not look good. 

[pytest-output.txt](https://github.com/joshgoebel/keyszer/files/8885038/pytest-output.txt)

But it worked better when I went through and manually pasted each line from the script to make sure I was inside the `venv` before installing the packages and running `pytest`. So maybe the "start" script is just not quite setting up the environment correctly before attempting to launch `keyszer`. Which is odd, because like I said I'm literally just copying and pasting the lines out of the script and running the same thing manually. Maybe it needs a `sleep` somewhere. 

[pytest-output-good.txt](https://github.com/joshgoebel/keyszer/files/8885048/pytest-output-good.txt)

**Comment by RedBearAK** [comment] 2022-06-12 02:33
No, pretty sure the script was working fine. It sets up the `venv` every time and makes sure everything is installed/refresh. I saw there's a trick with "dot" where I can source the script and make it run in the same shell. It definitely does the `venv` and everything as it's supposed to. 

Anyway, all key presses are outputting and nothing goes wrong until I hit something that qualifies as a "shortcut", then it goes crazy with the loop. Still doing the same thing.

**Comment by joshgoebel** [comment] 2022-06-12 02:38
Logs?

**Comment by joshgoebel** [comment] 2022-06-12 02:40
Can you fix it by shrinking your config file?  Figure out which part causes the problem?

**Comment by RedBearAK** [comment] 2022-06-12 03:07
I did start by typing a bunch of regular keys, which looked like the pasted output from above. Then I did Cmd+A and it went nuts. I don’t think it’s a problem with the config file. 

Will try to set up the debug key and get a log when I get back home.

**Comment by RedBearAK** [comment] 2022-06-12 04:02
[keyzser-output-2022-06-11-194637.txt](https://github.com/joshgoebel/keyszer/files/8885159/keyzser-output-2022-06-11-194637.txt)

[keyszer-output-2022-06-11-194637.zip](https://github.com/joshgoebel/keyszer/files/8885170/keyszer-output-2022-06-11-194637.zip)


3MB output and 125K lines on a run less than 30 seconds. Compresses down to 17KB as a Zip, so almost completely redundant lines. 

Maybe it has something to do with my config, but I'm still having no issues with Kinto's branch.

**Comment by joshgoebel** [comment] 2022-06-12 04:35
Well all these KeyErrors are a big red flag :)

**Comment by joshgoebel** [comment] 2022-06-12 04:42
```
  40 (+K) Grabbing AT Translated Set 2 keyboard (/dev/input/event4)
    41 (+K) Grabbing Keyszer VIRTUAL Keyboard (/dev/input/event15)
```

This is a massive problem... you are feeding Keyszer into itself... I should make sure that's not possible. :-)  OK, so this is some real progress.  You also can't have any keys depressed when the software starts, but that error is probably a red herring, but still something I should fix.

**Comment by joshgoebel** [comment] 2022-06-12 04:47
So I wasn't seeing the issue because I'm listing my devices manually (to include my mouse) and what broke was the auto-detection of devices, creating a feedback loop...

**Comment by joshgoebel** [comment] 2022-06-12 04:48
f8f3e08

**Comment by RedBearAK** [comment] 2022-06-12 05:06
OK, not doing too bad now. Most things are working fine. But I did run into an issue that appeared to be a stuck modifier problem where I was trying to scroll in a text file in GNOME's new text editor, and it zoomed the text. Can't replicate the effect with modifier keys so I'm not even sure which key it was. (Edit: Looks like holding logical Ctrl+Shift together will produce that effect. So both keys had to have been stuck.)

Typing just now the Shift key got stuck, acting like CapsLock, but CapsLock doesn't effect punctuation and it was turning single quote into double quote, so it was definitely the Shift key. 

And while typing this I seem to be having a few keystrokes going missing, including Space characters a few times, and just as I write this sentence the Space key got stuck and started repeating (I erased it). 

Going back to Kinto's branch for now. 

Here is the whole output from that run lasting a few minutes. Much more reasonable size. 

[keyszer-output-2022-06-11-205014.txt](https://github.com/joshgoebel/keyszer/files/8885226/keyszer-output-2022-06-11-205014.txt)

**Comment by joshgoebel** [comment] 2022-06-12 05:22
I generally can't do much with large logs like this... it was fine to help resolve your core issue... but if you want to help troubleshoot these individual issues I need small (as small as possible) pieces of the log with re-producible test cases... ie you need to find out which patterns result in the stuck keys (or other glitches) and then find out how to reproduce the problem.

From there I can reproduce it, write test cases, etc... fix it.  Just knowing there are 5 issues in a huge log is a bit of a needle in the haystack kind of problem unfortunately.

> and while typing this I seem to be having a few keystrokes going missing

This is sounding a lot like your prior problem with input getting lost... and I'm starting to wonder if I'd even notice if a key dropped once in a blue moon - I surely would if it got "stuck" but not if both sides of the event got dropped (or the press was dropped so only the release was seen)... I make enough typos periodically that I think it might just blen into the noise. 😕

I thought perhaps it dropped the "d" there, but I went back quickly and looked and it was me, not the software. (not saying that's your case)

**Comment by joshgoebel** [comment] 2022-06-12 05:24
So to be of continued help you'd almost need to find some way to "daily drive" my fork I think... first priority would be figuring out your dropped stuff... and it woudln't surprise me if that fixed your remaining issues... I wonder if you just added a delay back to the output if it would help?

One thing we could do is add a SECOND hotkey... instead of "abort" it could log a detailed diagnostic of the full state of the system... that might be useful but you'd have to be using the system, have a log, identify a problem quickly and hit the "dump diag" key... that might allow us to focus on the 5 places in the log with the actual issues.

**Comment by joshgoebel** [comment] 2022-06-12 05:26
cf808ba might help a bit if there is some weird overflow issue.

**Comment by RedBearAK** [comment] 2022-06-12 06:16
You know, I have to wonder if the "lost keystrokes" issue isn't the entire basis of the stuck keys problem. This system seems to have a remarkable ability to lose a large percentage of keystrokes. Every time one of those key events is a modifier release, that modifier would just act like it's being held down from then on, until it gets pressed again. Right? 

Then again, with things like Cmd+Shift+Tab it's still misbehaving badly. I don't think that's about the lost keystrokes. Still getting stuck modifiers after invoking the reverse (Shift) variants. This is with the latest pull after the new commit. 

Start with Cmd+Tab, move to Cmd+Shift+Tab, task manager still wants to stay visible most of the time. Then going into the app, the Alt and usually Shift act like they are still held. 

Is there some specific reason why I can never seem to stop `keyszer` with Cmd+dot (Ctrl+C), even though I'm always running it in a terminal just like I run Kinto's branch in another terminal? I always use Cmd+dot to kill the Kinto branch. 

I tried to do a run where I just invoked Cmd+Tab, then Cmd+Shift+Tab, then quit. But the log in that case is blank, besides my "KINTO RUNNING NORMALLY" banner.

**Comment by joshgoebel** [comment] 2022-06-12 06:27
> that modifier would just act like it's being held down from then on, until it gets pressed again. Right?

Yes, and the new DIAG key should tell you whether we're the one the key is stuck in or if it's stuck higher up, in the X layer.  If it's shown in _pressed_mods in the OUTPUT when it shouldn't be then it's stuck on our side.

> Is there some specific reason why I can never seem to stop keyszer with Cmd+dot (Ctrl+C)

No ideas, I don't see that combo and the actual keyboard CTRL-C works for me here:

```
(II) in LEFT_CTRL (press)
(DD) on_key LEFT_CTRL press
(DD) suspending keys [LCtrl<Key.LEFT_CTRL>]

(II) in C (press)
(DD) on_key C press
(OO) press LEFT_CTRL
(OO) press C
signal INT received
(OO) release LEFT_CTRL
(OO) release C
```

**Comment by joshgoebel** [comment] 2022-06-12 06:31
> Start with Cmd+Tab, move to Cmd+Shift+Tab, task manager still wants to stay visible most of the time. Then going into the app, the Alt and usually Shift act like they are still held.

Confirmed via the new DIAG.  :-)  Already super useful.

**Comment by RedBearAK** [comment] 2022-06-12 06:46
All Cmd+dot or physical Ctrl+C are doing for me are entering `^C` over and over again in the terminal. Neither will cause the running `keyszer` process to quit. I even tried removing the final command from the script and issued it manually after letting the script create/activate the `venv` and make sure all the prerequisites are installed. Still can't quit it with Ctrl+C. I don't know what that's about. It's happened a few times but it's pretty unusual for something I run in a terminal to refuse to listen to the interrupt signal. 

>Confirmed via the new DIAG. :-) Already super useful.

Alright, so you don't need the log from my previous run where all I did was Cmd+Tab around a bit and then Cmd+Shift+Tab? It's fairly short. 

[keyszer-output-2022-06-11-223539.txt](https://github.com/joshgoebel/keyszer/files/8885343/keyszer-output-2022-06-11-223539.txt)

**Comment by joshgoebel** [comment] 2022-06-12 06:47
> Alright, so you don't need the log from my previous run 

Nope, it's trivial to reproduce.

**Comment by joshgoebel** [comment] 2022-06-12 07:22
4 bugs later, 2 sticky bugs and 2 spent key bugs.  Seems much better now.

**Comment by RedBearAK** [comment] 2022-06-12 08:32
Things do not seem to be getting stuck now when switching to Cmd+Shift+Tab after Cmd+Tab. 

Starting with Cmd+Shift+Tab still misbehaves rather than bringing up the task switcher, but I suppose you know that already. 

As described in the Unicode thread, your branch appears to be passing through the input shortcut rather than attempting to do this macro: 

```
    K("Alt-Key_1"): [K("Shift-C-u"), K("Key_0"), K("Key_0"), K("a"), K("Key_1"), K("Enter")],
```

Not specifically related to the task switcher issue, which seems like it may be fixed. 

Well no, title included the "failing to appear" which is still happening. Cmd+Tab or Cmd+Grave show the task switcher and let you choose the app icon or preview thumbnail to switch to, respectively, before any switching happens. The Shift variants are still immediate, with no task switcher. 

Escape works to back out of the task switcher without switching. So that's good.

**Comment by RedBearAK** [comment] 2022-06-12 08:43
And now I can't Cmd+click on anything, even if I hold the modifier for much longer than 1 second. Terminal will start spewing lines if I hold Cmd for a while, so something obviously still changes after the suspension time is over, but Cmd+click just never works. 

This is unlike earlier iterations where I could hold for 1 second and then click.

**Comment by joshgoebel** [comment] 2022-06-12 08:49
Yeah. I noticed I broke suspend/resume a bit. 😥

**Comment by joshgoebel** [comment] 2022-06-12 12:12
I'm going to close this one and we can start a new thread.  I'll work on the suspend/resume tomorrow... after that though we need a plan for this... it doesn't make any sense to get this stuff perfect if ths entire solution is flawed.

**Closed by joshgoebel** 2022-06-12 12:12 UTC
