### ISSUE TITLE
Ctrl + Mouse left click delay issue.

### ISSUE THREAD

**Issue by zw963** [joshgoebel/keyszer#111] opened 2022-10-12 17:36 UTC
Hi, i use keyszer recent days, it work quite well.

But, i meet a new issue when enable keyszer, following is reproduce:

1. Open file manager, for me, i use Arch Linux + GNOME 3, which is, `files`, but i consider this issue can be reproduce for any file manager.
2.  Open a folder which exists many files
3.  Pressing Ctrl + mouse left click, to select files.
4. You will find when click to select multi-files, it not work, when select a new file, old file is deselect. as the Ctrl key not pressed.
5. but, after 1~2 seconds, multi-select with Ctrl + mouse left click start work.

I can reproduce the Ctrl + mouse left click exists delay issue. if disable keyszer, all work like a charm.

Thanks

**Comment by joshgoebel** [comment] 2022-10-15 09:10
This is intentional behavior, and this is a duplicate of: https://github.com/joshgoebel/keyszer/issues/16

If you want modifier-clicks to work you'll need to either reduce the delay or route your mouse clicks thru Keyszer so it can "see" them... see issue 16.

**Closed by joshgoebel** 2022-10-15 09:10 UTC
Labels: bug, help welcome

**Comment by zw963** [comment] 2022-10-15 11:27
It works, thank you.

following is some snippets to make this automate.

```sh
mouse_list=$(command ls -t /dev/input/by-path/*-event-mouse |xargs readlink -e |tr '\n' ' ')

~/.local/bin/keyszer -d $grabbing_device $mouse_list -c $ROOT/config_new.py "${@}"
```
