### ISSUE TITLE
Request: Nested keymaps should have entry trigger/actions

### ISSUE THREAD

**Issue by joshgoebel** [joshgoebel/keyszer#65] opened 2022-07-14 03:11 UTC
@joshgoebel 

There is another aspect of the Option key special character entry in macOS that I would like to be able to mimic. It's possible with AutoHotKey already. But I don't know how difficult it would be to add it to the way `keyszer` processes nested shortcuts. You can actually do fairly complex actions with AHK after the initial combo, including sending some keys, and then still be waiting to trigger one of the second layer of combos or keys. 

Right now I don't think there is a way to run a command or send out some keystrokes immediately after the initial/outer layer of the nested shortcut is invoked, and then continue to process the second layer of combos/keys. 

An example of the way this would look is Option+Grave would place a visible Grave character so the user can see it, then the key pressed after that would send out a Backspace to erase the Grave character and replace it with the accented character. This is how it works in macOS. You can see the accent that is about to be applied to the next key. 

Or, the accent is actually placed in a highlight in macOS, which makes it even more intuitive that the next character will replace it. So the most precise way to mimic this might be to output the Grave, do Shift+Left, and then wait for the next key, which will then overwrite the highlighted accent character. This is easy to do with a macro, but only at the second level of nesting, so it's fairly pointless and would just be for show. 

```python
    C("Alt-Grave"): {                       # Dead Keys Accent Grave
        C("A"):                     [UC(0x0060),C("Shift-Left"),sleep(0.3),UC(0x00E0)],     # à Latin Small a with Grave
    },
```

In its current form, the Option-key schemes for both Windows and Linux don't attempt to do anything like this. So the user sees nothing in output until you press the second key in the dead keys sequence. It makes the dead keys usage less intuitive than it is on macOS, if you're not already familiar with the accent keys. 

If there is already a syntax that would perform an action for the initial nested shortcut and then continue on to process the inside layer(s) of nested shortcuts afterward, let me know.

_Originally posted by @RedBearAK in https://github.com/joshgoebel/keyszer/issues/61#issuecomment-1183859002_

**Comment by joshgoebel** [comment] 2022-07-14 03:17
> you can actually do fairly complex actions with AHK after the initial combo

A trigger? That wouldn't be that hard to add, would it?  We'd need a good name/namespace for it...

```py
C("Alt-Grave"): {
  Trigger.onEnter: Key.GRAVE, 
  C("A"): # whatever combo stuff
},
```

Then when transitioning to the next keymap if a `onEnter` trigger was found in that keymap it would immediately be executed.  See the if/else dispatch in `handle_commands`.


```

**Comment by RedBearAK** [comment] 2022-07-14 04:13
@joshgoebel 

> entry trigger?

Yeah, that's pretty much it. If that can still handle arbitrary Python commands, keys, combos and macros like you might use on any other line after the colon, that would take care of it. And I don't know why it wouldn't. That would bring potential functionality very similar to what I had available in AHK. 

I don't immediately see anything wrong with the naming. Maybe a `Trigger.noMatch` would take care of the "Default/any" scenario. Seems fairly intuitive terminology, at least. So I might do something like this with that: 

```python
C("Alt-Grave"): {
  Trigger.onEnter: [C("Grave"),C("Shift-Left")],    # Show Grave char, highlight with cursor
  Trigger.noMatch: [C("Right"), UserInput],     # No valid key, deselect Grave char, pass combo/key
  C("A"): UC(0x00E0),     # à Latin Small a with Grave
},
```

I'm not sure if there might be a use for a `Trigger.onExit` separate from a `noMatch`, or if these by necessity would be the same thing, triggering an action upon leaving the keymap without matching anything else.

**Comment by RedBearAK** [comment] 2022-08-12 03:01
Need yet another type of action for nested keys to completely "close the loop" so to speak. But I don't know how feasible this one would be. 

Possible naming: 

```
Trigger.repeat
Trigger.loop
Trigger.return
```

As this implies, basically it would be a way to "restart" the nest process (instead of just escaping from it with or without performing any action), and re-perform any initial trigger actions (if there are any), and then be back in the state of waiting for one of the inner keys/combos to be used. In other words, make the nest "loopable" with the appropriate trigger. 

Why: If you use the outer shortcut (a "dead keys" shortcut) like Opt+Grave on macOS, and then repeat that same combo, it will deposit the accent diacritic character by itself and then put a new highlighted accent next to it. This is different behavior from what you get if you hit things like Escape or Space, which just ends the nesting process. Without being able to return to the outside of the nested keys construct, there's no way to mimic this other than just adding more layers of redundant nesting, ad infinitum. Obviously undesirable. 

I'm guessing this would require some sort of caching of the original "outer" key/combo that begins the nested keys process, so that the process can just keep repeating when the "loop" trigger is used. Otherwise I would suppose there's no way to go "backwards" in the current recursive process that handles nested keys. 

In my use case the loop trigger would be the same as the original combo, but I can see others possibly wanting to have a different key/combo loop the nesting. So, while it could work with just something like `Trigger.repeat: True`, which could just watch for the same (cached) original key/combo that triggered the nest construct in the first place, it should also be able to handle a different specified key or combo. I wouldn't want to limit the possible use cases. 

```python
C("Alt-Grave"): {
    Trigger.repeat: True,
},

C("Alt-E"): {
    Trigger.repeat: C("R"),
},
```

**Comment by joshgoebel** [comment] 2022-08-12 06:04
Individual examples of these 3 things and how they might be used and behave would be helpful.  Just looking at your last code snippet I have no idea what either is supposed to do exactly..

**Comment by RedBearAK** [comment] 2022-08-12 08:12
> Individual examples of these 3 things and how they might be used and behave would be helpful. Just looking at your last code snippet I have no idea what either is supposed to do exactly..

It "repeats" the nesting from the beginning. 

I suppose without a `Trigger.onEnter` action this would appear to do nothing in particular, but you would still just be inside the inner nested structure waiting for a nested key press, rather than having left the inner structure and canceled the nesting. 

The three different naming suggestions are for the same thing. I'm leaning toward `Trigger.repeat` being the clearest for what this would be doing. `Trigger.return` implies actually leaving or canceling the nested keys process, and `Trigger.loop` implies a continuous repeating, which isn't the intent. Though for all I know someone might have a use for that separately, staying inside a looping nest until exited with a specific key. 🤷🏽‍♂️ 

```python
C("Alt-Grave"): {
    Trigger.onEnter: C("Grave"),  # ` Leave accent character
    Trigger.repeat: True,  # Start over (repeat onEnter action, if present)
    C("A"):  UC(0x00E0),  # à Latin Small a with Grave
},

C("Alt-E"): {
    Trigger.onEnter: UC(0x00B4),  # ´ Leave accent character
    Trigger.repeat: C("R"),  # Start over (repeat onEnter action, if present)
    C("A"): UC(0x00E1),  # á Latin Small a with Acute
},
```

This would leave the accent diacritic over and over every time you used the initial combo (or "repeat" trigger, if different), but it would always still be waiting for the next key inside the nesting. Or Escape or Space, or any other key that will break out of the nesting. 

Right now what happens if you repeat the original combo is that it just leaves the nesting without doing anything. So the next keystroke is normal, no accent. And since there's no `onEnter` kind of action available yet, the state of the dead key nesting is invisible to the user. At the very least if the nesting were repeatable after using the same combo again, the user would always get an accented character after using the combo, even if they got distracted and forgot they already did it earlier.

**Comment by RedBearAK** [comment] 2022-08-17 09:22
```python
C("Alt-Grave"): {
    Trigger.onEnter: C("Grave"),  # ` Leave accent character
    C("Alt-Grave"): [C("Grave"), remain_here_dont_return_parent],
    C("A"):  UC(0x00E0),  # à Latin Small a with Grave
},
```

This way of doing it would actually solve an issue I had thought of, which was that I kind of needed something slightly different to happen on the first run-through than what should happen on any subsequent run-through cycles. This structure would make that relatively easy to accomplish. 

I'm guessing this is not restarting and "looping" the nest but rather just avoids leaving this level of the nesting until an input is used that will trigger moving on. Slightly different from what I was thinking. Less limited. 

A simple `remain_here` naming, if documented properly, would probably work well enough for most users that need it to grasp what it does for them. Or, if you think most users will grasp the functioning of the app better than me, maybe just stick with `dont_return_parent`. That's pretty functional.

**Comment by joshgoebel** [comment] 2022-08-20 15:48
So first lets agree that the current behavior is correct... should the first combo matched inside a sub-group always return to top?  Because another way to do this would be to always require a return:

```
C("Alt-Grave"): {
    Trigger.onEnter: [C("Grave"), return_top],  # ` Leave accent character
    C("Alt-Grave"): C("Grave"),
    C("A"):  [UC(0x00E0), return_top]   # à Latin Small a with Grave
},
```

Did we consider this at all?

---

If we go with the "no_return_root" this should be something you could add I'd think... just model it after `ignore_key` except you want to return False instead of true...  we're kind of forcing these commands to always come at the end of a sequence, but for now I think that's OK...

**Comment by joshgoebel** [comment] 2022-08-20 15:51
Too bad these aren't arrays or we could start to get more "program like";

```py
C("Alt-Grave"): {
   type C("Grave"),  # ` Leave accent character
   map
       C("Alt-Grave"): C("Grave"),
        C("A"):  UC(0x00E0),   # à Latin Small a with Grave,
    return_top
},
```

Is that more like the Windows thingy?

**Comment by joshgoebel** [comment] 2022-08-20 16:00
Oh the whole mapping could be a lambda and just python code:

```
def do_grave(ctx):
   ctx.out(C("Grave"))
   apply_map({       
     C("Alt-Grave"): C("Grave"),
     C("A"):  UC(0x00E0) })
   ctx.return_top

C("Alt-Grave"): do_grave()
```

Except that isn't quite right since `return_top` (as pointed out earlier) is more of a config, not something that can be done immediately... unless we get into async and such stuff here, which is a direction I don't want to go...

**Comment by joshgoebel** [comment] 2022-08-20 23:17
@RedBearAK Please review #80 for trigger on entry... and pay careful attention to the test - is that what we're expecting?

**Comment by RedBearAK** [comment] 2022-08-20 23:31
Very interesting ideas. The one thing I would say at this stage is that most users would probably not appreciate a nesting system that made it too easy to get stuck in a loop if you forget to add the exit command on every single line that should leave the nesting. 

The “array” version still looks pretty clean to me. The defined function version is probably closest to what I ultimately ended up with in AHK. But if you were going to go to that point surely it would be just as easy to modify the existing handler. 

I’m leaning strongly toward the array version.

**Comment by RedBearAK** [comment] 2022-08-20 23:46
> Please review

I’ll try it out when I get back to the house. Not doing the ‘Trigger.onEnter` kind of naming? I rather like that.

**Comment by RedBearAK** [comment] 2022-08-21 01:46
Alright, all the stuff I was messing with has been merged so I just went back to main and pulled, then checked out the new branch. 

I added a test line to my existing Option key scheme: 

```python
    C("Alt-Grave"): {                       # Dead Keys Accent Grave
        immediately:                UC(0x0060),
        C("Esc"):                   UC(0x0060),     # ` Leave accent character if dead keys Escaped
        C("Space"):                 UC(0x0060),     # ` Leave accent character if user hits Space
        C("Grave"):                 [UC(0x0060),UC(0x0060)],    # Output two Graves if Grave is next key
        C("A"):                     UC(0x00E0),     # à Latin Small a with Grave
...
```

Seems to react as expected, for an entry trigger. Subsequent attempt to use Opt+Grave will of course do nothing since it doesn't match anything, so it just exits the nesting, and then doing it again will do the entry trigger action because it all starts over from scratch. 

Macro also working, which gets close to mimicking most of the macOS dead key behavior. 

```python
        immediately:                [UC(0x0060),C("Shift-Left")],
```

Place Grave character, highlight, then Escape or Space will overwrite the highlighted character (with the same character) and leave the cursor next to it. 

Yep. All working fine. 

The tricky one is if you do the original Opt+Grave again. It should do what Escape or Space does, but then place a new Grave and highlight it, and stay within the nesting. 

As for naming, `onEnter` really seems the most intuitive to me. As in, "when you come in here, do this". The "immediately" seems a bit abstract. Something like `entry_action` would also make a lot of sense to me.

**Comment by RedBearAK** [comment] 2022-08-21 02:10
Oh, this is neat, the nesting was of course interfering with task switching. If you try to switch away during the dead keys process, nothing happens on the first attempt. I was able to get it to exit the nesting and switch away as if it was perfectly normal. 

```python
    C("Alt-Grave"): {                       # Dead Keys Accent Grave
        immediately:                [UC(0x0060), C("Shift-Left")],      # onEnter trigger: insert Grave, highlight
        C("Esc"):                   UC(0x0060),     # ` Leave accent character if dead keys Escaped
        C("Space"):                 UC(0x0060),     # ` Leave accent character if user hits Space
        C("Tab"):                   [UC(0x0060), C("Tab")],                     # ` Leave accent char, insert Tab
        C("RC-Tab"):                [UC(0x0060), bind, C("Alt-Tab")],           # ` Leave accent char, task switch
        C("Shift-RC-Tab"):          [UC(0x0060), bind, C("Shift-Alt-Tab")],     # ` Leave accent char, task switch (reverse)
        C("RC-Grave"):              [UC(0x0060), bind, C("Alt-Grave")],         # ` Leave accent char, in-app window switch
        C("Shift-RC-Tab"):          [UC(0x0060), bind, C("Shift-Alt-Grave")],   # ` Leave accent char, in-app window switch (reverse)
        C("Grave"):                 [UC(0x0060),UC(0x0060)],                    # `` Output two Graves if Grave is next key
        C("A"):                     UC(0x00E0),     # à Latin Small a with Grave
...
```

I think that it might be a good idea at some point to have a more general solution to that, specifically allowing the designated "task switching" combos to always escape a nested keys process even if it's not explicitly defined as an exit path. Nothing else really interferes with things like Cmd+Tab. 

But for my purpose I also need it to leave the accent character behind and remove the highlight, so this method works out just fine.

**Comment by joshgoebel** [comment] 2022-08-21 02:17
I'll give the name more thought but remember you can always just rename it by creating a variable that references it in the configuration.

**Comment by RedBearAK** [comment] 2022-08-21 23:58
Hmm, I think I was missing an aspect of what a need from the nested keymaps for the Option key scheme. I was only thinking about what should happen if I repeat the original combo, but in actuality that original combo is just one instance of the entire "dead keys" group of initiating combos. And, if I go ahead with implementing the "ABC Extended" keyboard layout there are actually about 25 dead keys rather than the 5 dead keys on the standard US layout. So it behooves me to find the simplest possible way to let all the other dead keys combos exit a currently engaged dead key nesting, without having to specify all 25 of them in 25 different nesting groups. 

There are two ways I can think of to solve this. One is going with defining the action of each dead key as a named function, sort of like the named subroutines I ended up with in AHK. Which was one of your suggestions, and I'm sure that could be made to work. 

The other is the "pass through user input if no match" idea, from earlier. Which should be able to handle this, including dealing with the user repeating the same original combo inside the nesting. If it doesn't match anything, it would perform the "exit_action", which can be a macro. If that default exit had the ability to come from inside the nesting for Opt+Grave and pass Opt+Grave, or Opt+E or any other dead key combo directly at the parent level, it should act effectively like calling a named function. 

For this specific use case that would mean that the "stay here" kind of action shouldn't actually be necessary. Although it would no doubt be useful in other circumstances (where you don't want to keep repeating the "entry_action"). There just needs to be a way for the exiting combo to remain "alive" rather than vaporizing into the æther as it pops the nested keymap out of existence. 

Right now, even if you explicitly place the combo to try and repeat the nesting, it doesn't activate at a level that allows it to re-activate the nested keymap. In this case the Alt+Grave in the macro attempts to do an in-app window switch. Which I suppose makes sense as it's on the right side of the colon. 

```python
    C("Alt-Grave"): {                       # Dead Keys Accent Grave
        entry_action:                [UC(0x0060), C("Shift-Left")],      # onEnter trigger: insert Grave, highlight
…
        C("Alt-Grave"):             [UC(0x0060),C("Alt-Grave")],                # ` Leave accent char, try to re-enter nested keymap
```

Maybe nested keymaps should just have defined names? Optionally?

**Comment by RedBearAK** [comment] 2022-08-22 01:51
If you know of other methods to define and use a variable within a keymap structure, let me know. Sticking it inside the macro like this seems to work, but it wanted the ':=" assignment operator that I've only used in AHK before now. 

I wonder if there are other ways to set a variable inside a keymap or nested keymap. These aren't exactly normal function structures, so the usual method of just plopping `var = value` on its own line doesn't work. 

```python
    C("Alt-N"): {                                   # Dead Keys Accent Tilde
        entry_action:              [ac_Chr:=0x02DC, UC(ac_Chr), C("Shift-Left")],      # onEnter trigger: insert Grave, highlight
        C("Esc"):                   UC(ac_Chr),     # ` Leave accent character if dead keys Escaped
        C("Space"):                 UC(ac_Chr),     # ` Leave accent character if user hits Space
        C("Delete"):                UC(ac_Chr),     # ` Leave accent char if user hits Delete (not Backspace)
        C("Backspace"):            [UC(ac_Chr), C("Backspace")],                # Delete character if user hits Backspace
        C("Tab"):                  [UC(ac_Chr), C("Tab")],                      # ` Leave accent char, insert Tab
        C("Up"):                   [UC(ac_Chr), C("Up")],                       # ` Leave accent char, insert Tab
        C("Down"):                 [UC(ac_Chr), C("Down")],                     # ` Leave accent char, insert Tab
        C("Left"):                 [UC(ac_Chr), C("Left")],                     # ` Leave accent char, insert Tab
        C("Right"):                [UC(ac_Chr), C("Right")],                    # ` Leave accent char, insert Tab
        C("RC-Tab"):               [UC(ac_Chr), bind, C("Alt-Tab")],            # ` Leave accent char, task switch
        C("Shift-RC-Tab"):         [UC(ac_Chr), bind, C("Shift-Alt-Tab")],      # ` Leave accent char, task switch (reverse)
        C("RC-Grave"):             [UC(ac_Chr), bind, C("Alt-Grave")],          # ` Leave accent char, in-app window switch
        C("Shift-RC-Tab"):         [UC(ac_Chr), bind, C("Shift-Alt-Grave")],    # ` Leave accent char, in-app window switch (reverse)

        C("A"):                     UC(0x00E3),     # ã Latin Small a with Tilde
        C("N"):                     UC(0x00F1),     # ñ Latin Small n with Tilde
        C("O"):                     UC(0x00F5),     # õ Latin Small o with Tilde
        C("Shift-A"):               UC(0x00C3),     # Ã Latin Capital A with Tilde
        C("Shift-N"):               UC(0x00D1),     # Ñ Latin Capital N with Tilde
        C("Shift-O"):               UC(0x00D5),     # Õ Latin Capital O with Tilde
    },
```

**Comment by joshgoebel** [comment] 2022-08-22 13:36
Nope. Of course you can always set the variable before the key map call.

**Comment by joshgoebel** [comment] 2022-08-22 14:37
`[ac_Chr:=0x02DC,`

This is not a valid command, so I would not recommend this.  It's likely something we should explicitely disallow.

**Comment by RedBearAK** [comment] 2022-08-22 20:37
> Nope. Of course you can always set the variable before the key map call.

Yes, but the problem is that the entire Option key scheme, and thus all the nested "dead key" blocks, are all inside the same `keymap`. I wanted to create a more abstract block for the exit keys that are the same for each dead key, and then just set the resulting Unicode character address once at the top of each block. 

> This is not a valid command, so I would not recommend this. It's likely something we should explicitly disallow.

Well, that would kill my ability to set a variable within a nested keymap, unless you have some other way of doing it. 

I at first tried to set up 5 different variables outside the keymap, but that would mean each nested dead key block would have to reference a different variable and it would be much more difficult to copy and paste the exit key block as it evolved. Of course everything would get much worse if I tried to support the "ABC Extended" layout with its 25 dead keys. 

I thought about abstracting this out into a function, but I'm pretty sure I would still need the same number of lines inside the nested keymap to call the function in a meaningful way, so I don't think that would actually simplify anything. Unless I could blindly pass in the key or combo to the function on a single line, along with the Unicode value, and have it come back into the nested keymap to continue evaluating the rest of the nested keymap if there was no match inside the function. But that sounds too complicated for me to implement right now. 

Wait, maybe I can call a really simple function with the entry trigger that does nothing but set the variable to the given input and come back. 🤔 That would be a "valid command", I assume.

**Comment by joshgoebel** [comment] 2022-08-22 21:39
> is that the entire Option key scheme, and thus all the nested "dead key" blocks, are all inside the same keymap

_Of course it doesn't have to be that way._  This is all just Python, you could build the Keymaps individually and then insert them into a larger keymap... 

> and then just set the resulting Unicode character address once at the top of each block.

I've seen this (localized constants) but if the constant is well-named (and a true constant) I'm not sure why locality matters all that much.  The best constants (names) are stand-ins for the value... someone should know all they need to know seeing the constant name - they shouldn't need to find the value nearby.  If that was the case I'd suggest you needed a better name.

> I thought about abstracting this out into a function, but I'm pretty sure I would still need the same number of lines inside the nested keymap to call the function in a meaningful way, 

Why?

> Wait, maybe I can call a really simple function with the entry trigger that does nothing but set the variable to the given input and come back. 

That might work.

**Comment by RedBearAK** [comment] 2022-08-22 22:30
> I've seen this (localized constants) but if the constant is well-named (and a true constant) I'm not sure why locality matters all that much. The best constants (names) are stand-ins for the value... someone should know all they need to know seeing the constant name - they shouldn't need to find the value nearby. If that was the case I'd suggest you needed a better name.

This whole paragraph confuses me. The variable I ended up with has the same name in all 5 dead keys blocks, so within the overall keymap it can't be called a constant. It sets itself to a different value for each nested group that gets activated. It's just a shortened form of "accent_character" to fit within the same space as the usual Unicode address. 

> Of course it doesn't have to be that way. This is all just Python, you could build the Keymaps individually and then insert them into a larger keymap...

Yes. That's a slightly different way of thinking about it than what I was thinking. Probably what I will end up doing. Still kind of a pain to "build" a keymap that way, but with the number of times I'll be repeating the same block it makes a lot more sense to go to the trouble.

**Comment by joshgoebel** [comment] 2022-08-22 22:48
>  It sets itself to a different value for each nested group that gets activated.

Yeah you're doing something else then. :-)   I misundertood.

**Comment by RedBearAK** [comment] 2022-08-29 11:33
@joshgoebel 

This has gotten pretty long, and I think the merging of the immediate trigger pretty much takes care of the primary feature request. There's issue #63 for the "pass through" of input that will be needed for a "Default/any" trigger option to be more useful. 

Think this can be closed.

**Closed** 2022-08-29 11:50 UTC
Labels: enhancement, help welcome, good first issue
